[AEROGEAR-2184] Add check if client exists before deleting it
aerogearcatalog/cordova-app-apb pull request #4
Opened 2018-03-13 11:16 UTC by JameelB

## Description
Add a check if the client exists before attempting to delete it. If the client has already been removed, skip the deletion.

## Progress
- [x] Change type from android to cordova on provision
- [x] Add check if client exists before deleting

## Additional Notes
Related JIRA Ticket - https://issues.jboss.org/browse/AEROGEAR-2184

2018-03-13 14:49 UTC, vchepeli requested changes

2018-03-13 14:49 UTC, vchepeli commented on roles/deprovision-cordova-app/tasks/main.yml
> +- set_fact: app_not_found_err="'mobileclients.mobile.k8s.io \"{{ appName }}-cordova\" not found'"
This can be `set_fact: app_not_found_err='mobileclients.mobile.k8s.io "{{ appName }}-cordova" not found'`

2018-03-13 14:49 UTC, vchepeli commented on roles/deprovision-cordova-app/tasks/main.yml
> +  failed_when: mobile_client.stdout == "" and not mobile_client.stderr | search({{ app_not_found_err }})
use `not ()` e.g. `not (mobile_client.stderr | search(app_not_found_err)` and you dont need to use `{[...}}` inside `failed_when` statement

2018-03-13 14:49 UTC, vchepeli commented on roles/deprovision-cordova-app/tasks/main.yml
> +  when: mobile_client.stderr == ""
you can also use `mobile_client.stderr|length == 0` but it should be defined

2018-03-13 17:06 UTC, maleck13 approved these changes

2018-03-14 10:23 UTC, vchepeli approved these changes

2018-03-14 10:23 UTC, vchepeli commented on roles/provision-cordova-app/tasks/main.yml
> +  shell: mobile create client {{ appName }} cordova {{ appIdentifier }} --namespace={{ namespace }}
wow, that good catch!

2018-03-14 10:51 UTC, merged